### ISSUE TITLE
Configurable features

### ISSUE THREAD

**Issue by V1ncNet** [kammerchor-wernigerode/participate#11]
To ensure better feature management each features should get its own namespace and enabled-flag. 

```yaml
app:
  feature:
    overdue-reminder:
      enabled: true
      cron: 0 0 9 ? * SUN
    scores-manager-notification:
      enabled: false
```

This also fixes #9.
